### ISSUE TITLE
Рейтинг можно увеличивать/уменьшать бесконечно

### ISSUE THREAD

**Issue by irrvrsl** [Archakov06/rgxp#1]

**Comment by Archakov06** [comment]
Пока серверная на mockapi.io и с этим ничего не поделать. Чуть позже поставлю на свой сервак RESTful API для rgxp.ru

**Comment by devlato** [comment]
@irrvrsl @Archakov06 точнее, можно просто отправить `PUT`-ом любое значение (что я и сделал), и никакой валидации нет

**Comment by Archakov06** [comment]
@devlato временно уберу рейтинг и подгрузку паттернов, сделаю из статичного файла, который на репе будет храниться. Как запилю серверную, подключу рейтинг и кое-какие еще фичи.

**Comment by devlato** [comment]
@Archakov06 отлично)
