### ISSUE TITLE
Шаблон валидации Email Устарел

### ISSUE THREAD

**Issue by sinneren** [Archakov06/rgxp#9]
Например, для домена .group не срабатывает

**Comment by Archakov06** [comment]
Есть что предложить?

**Comment by sinneren** [comment]
@Archakov06 так просто в конце {2,3} На {2,5} заменить. Хотя бы для начала. Очень много доменов не проскальзывают, те же Info, media

**Comment by Archakov06** [comment]
Обновил регулярку. Теперь поддерживает домены `.media`, `.business` и т.п. = {2, 8}

**Comment by sinneren** [comment]
Вообще, есть стандарт определенный и рабочий, в котором всё это учтено:
https://gist.github.com/gregseth/5582254
